@startuml
[*] --> Rellotge_Normal


state Configuarar_Hora {


Rellotge_Normal --> Cambiar_hora : pulsar A
Cambiar_hora --> Accio_CambiarHora_b : pulsar B
Cambiar_hora --> CambiarMinutos_a : pulsar A
CambiarMinutos_a --> Accio_CambiarMinutos_b : pulsar B
Cambiar_hora : Fa  llum la hora
Accio_CambiarHora_b --> Accio_CambiarHora_b : pulsar B
Accio_CambiarHora_b --> CambiarMinutos_a : pulsar A
Accio_CambiarMinutos_b --> Accio_CambiarMinutos_b : pulsar B
Accio_CambiarMinutos_b --> [*] : pulsar A
  
}
       

@enduml
